project:
  type: website
  output-dir: docs

website:
  title: "Benjamin (songhao) Ma’s Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: Blog.qmd
        text: Projects
      - href: certificates.qmd
        text: Certificates

format:
  html:
    theme: cosmo
    css: styles.css       # ← this line must point to your styles.css
    toc: false
