<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Benjamin (songhao)Ma's Website – index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Benjamin (songhao)Ma’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html" rel="" target="">
 <span class="menu-text">resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Blog.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#this-is-project-6" id="toc-this-is-project-6" class="nav-link active" data-scroll-target="#this-is-project-6">This is Project 6</a>
  <ul class="collapse">
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#mnl-for-heterogenity" id="toc-mnl-for-heterogenity" class="nav-link" data-scroll-target="#mnl-for-heterogenity">MNL for Heterogenity</a></li>
  <li><a href="#illustrations" id="toc-illustrations" class="nav-link" data-scroll-target="#illustrations">Illustrations</a></li>
  <li><a href="#add-heterogenity" id="toc-add-heterogenity" class="nav-link" data-scroll-target="#add-heterogenity">Add Heterogenity</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary 1</a></li>
  <li><a href="#deeper-dive-into-the-data" id="toc-deeper-dive-into-the-data" class="nav-link" data-scroll-target="#deeper-dive-into-the-data">Deeper Dive into the data</a></li>
  <li><a href="#summary-2" id="toc-summary-2" class="nav-link" data-scroll-target="#summary-2">Summary 2</a></li>
  <li><a href="#add-heterogeneity-via-a-segment-interactions" id="toc-add-heterogeneity-via-a-segment-interactions" class="nav-link" data-scroll-target="#add-heterogeneity-via-a-segment-interactions">Add Heterogeneity Via a Segment Interactions</a></li>
  <li><a href="#summary-3" id="toc-summary-3" class="nav-link" data-scroll-target="#summary-3">Summary 3</a></li>
  <li><a href="#brand-dummy-and-price-models" id="toc-brand-dummy-and-price-models" class="nav-link" data-scroll-target="#brand-dummy-and-price-models">Brand-Dummy and Price Models</a></li>
  <li><a href="#summary-4" id="toc-summary-4" class="nav-link" data-scroll-target="#summary-4">Summary 4</a></li>
  <li><a href="#comparing-brand-dummy" id="toc-comparing-brand-dummy" class="nav-link" data-scroll-target="#comparing-brand-dummy">Comparing Brand-Dummy</a></li>
  <li><a href="#summary-5" id="toc-summary-5" class="nav-link" data-scroll-target="#summary-5">Summary 5</a></li>
  <li><a href="#building-a-model-with-segment-specific-and-individual-specific-heterogeneity" id="toc-building-a-model-with-segment-specific-and-individual-specific-heterogeneity" class="nav-link" data-scroll-target="#building-a-model-with-segment-specific-and-individual-specific-heterogeneity">Building a Model with Segment-Specific and Individual-Specific Heterogeneity</a></li>
  <li><a href="#summary-6" id="toc-summary-6" class="nav-link" data-scroll-target="#summary-6">Summary 6</a></li>
  <li><a href="#which-models-predict-better" id="toc-which-models-predict-better" class="nav-link" data-scroll-target="#which-models-predict-better">Which models predict better?</a></li>
  <li><a href="#summary-7" id="toc-summary-7" class="nav-link" data-scroll-target="#summary-7">Summary 7</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="this-is-project-6" class="level1">
<h1>This is Project 6</h1>
<p>Extending the MNL model from previous project 5 data to include heterogeneity.</p>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
</section>
<section id="mnl-for-heterogenity" class="level2">
<h2 class="anchored" data-anchor-id="mnl-for-heterogenity">MNL for Heterogenity</h2>
<p>Define a function to visualize the probability that a customer will choose a specific phone, separated by different discount levels. We’ll begin by focusing on phone A1.</p>
<p>This visualization aims to highlight the differences in predicted preferences among individual customers. Each plot will have an x-axis displaying the predicted choice probability for the selected phone. Facets will categorize customers who encountered the same pricing conditions, specifically those who saw the same phones on discount.</p>
<p>A histogram will be used to depict the distribution of these choice probabilities among customers. Initially, this distribution might appear uniform in a homogeneous model but will display greater variation as we introduce elements of customer heterogeneity.</p>
<p>The function will be applied sequentially to different phones to observe how the histograms vary when different discounts are applied to different phones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Data Importing</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlogit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: dfidx

Attaching package: 'dfidx'

The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cust_dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./smartphone_customer_data.csv"</span>, <span class="at">show_col_types=</span>F)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(cust_dat) </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>phone_dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"./phone_dat.csv"</span>,<span class="at">show_col_types=</span>F)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/Desktop/MGT100 folder/mnl_datasets.RData"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"~/Desktop/MGT100 folder/mnl_performance_functions.RData"</span>)   </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  myplot <span class="ot">&lt;-</span> <span class="cf">function</span>(data, model, phone) {</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        disc_levs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A1"</span>, <span class="st">"A2"</span>, <span class="st">"S1"</span>, <span class="st">"S2"</span>, <span class="st">"H1"</span>, <span class="st">"H2"</span>, <span class="st">""</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        preds <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">predict</span>(model, <span class="at">newdata=</span>data))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        <span class="fu">colnames</span>(preds) <span class="ot">&lt;-</span> disc_levs[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        temp <span class="ot">&lt;-</span> cust_dat <span class="sc">|&gt;</span> </span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>            <span class="fu">filter</span>(years_ago <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">discount =</span> <span class="fu">factor</span>(discount, <span class="at">levels =</span> disc_levs)) <span class="sc">|&gt;</span> </span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">discount =</span> <span class="fu">fct_recode</span>(discount, <span class="st">"None"</span><span class="ot">=</span><span class="st">""</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">pr =</span> preds[[phone]]) <span class="sc">|&gt;</span> </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>            <span class="fu">select</span>(discount, pr)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        p <span class="ot">&lt;-</span> temp <span class="sc">|&gt;</span> <span class="fu">filter</span>(discount <span class="sc">!=</span> <span class="st">"None"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>             <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>pr)) <span class="sc">+</span> </span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>                <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">fill=</span>discount), <span class="at">binwidth =</span> <span class="fl">0.01</span>) <span class="sc">+</span> </span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>                <span class="fu">facet_wrap</span>(. <span class="sc">~</span> discount) <span class="sc">+</span> </span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>                <span class="fu">xlab</span>(<span class="fu">paste</span>(<span class="st">"Probability a customer chooses phone"</span>, phone)) <span class="sc">+</span> </span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>                <span class="fu">ylab</span>(<span class="st">"Count of customers"</span>) <span class="sc">+</span> </span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>                <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">"Pr(choose "</span>,phone,<span class="st">") by customer"</span>)) <span class="sc">+</span> </span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>                <span class="fu">labs</span>(<span class="at">fill =</span> <span class="st">"Discounted Phone"</span>) <span class="sc">+</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>                <span class="fu">theme_bw</span>() </span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>        <span class="fu">print</span>(p)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span>(<span class="fu">invisible</span>(<span class="cn">NULL</span>))</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate market shares </span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># In project 5 I did it, but it's helpful to have these as reference points</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>    brand_shares <span class="ot">&lt;-</span> cust_dat  <span class="sc">|&gt;</span>  </span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        <span class="fu">filter</span>(years_ago <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>        <span class="fu">count</span>(brand) <span class="sc">|&gt;</span> </span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">shr =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    brand_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  brand       n   shr
  &lt;chr&gt;   &lt;int&gt; &lt;dbl&gt;
1 apple     346 0.356
2 huawei    284 0.292
3 samsung   342 0.352</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>    product_shares <span class="ot">&lt;-</span> cust_dat <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">filter</span>(years_ago <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">count</span>(phone_id) <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">shr =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    product_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  phone_id     n    shr
  &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
1 A1         233 0.240 
2 A2         113 0.116 
3 H1         144 0.148 
4 H2         140 0.144 
5 S1         246 0.253 
6 S2          96 0.0988</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit homogeneous model from project 5</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    out4 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> phone_id <span class="sc">+</span> price <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(out4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ phone_id + price | 0, data = mdat1, 
    method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.000518 
successive function values within tolerance limits 

Coefficients :
             Estimate Std. Error z-value  Pr(&gt;|z|)    
phone_idA2  0.3324964  0.2212103  1.5031  0.132819    
phone_idH1 -1.2251497  0.1724673 -7.1037 1.215e-12 ***
phone_idH2 -0.9080016  0.1303339 -6.9667 3.244e-12 ***
phone_idS1 -0.3060387  0.1124682 -2.7211  0.006506 ** 
phone_idS2 -0.5545496  0.1346713 -4.1178 3.825e-05 ***
price      -0.0071582  0.0012933 -5.5346 3.119e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1668.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">brand_hit_rate</span>(mdat1, out4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.367284</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">product_hit_rate</span>(mdat1, out4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2685185</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ll_ratio</span>(mdat1, out4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0419071</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>    <span class="co"># plot each individual's probability of choosing phone A1</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">myplot</span>(mdat1, out4, <span class="st">"A1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="illustrations" class="level2">
<h2 class="anchored" data-anchor-id="illustrations">Illustrations</h2>
<p>I am examining the modifications in histograms of choice probabilities for Product A1 as phone discounts fluctuate. Currently, the homogeneous demand model does not reveal any correlation between predicted customer choice shares and their responses to discounts. However, this situation is expected to change.</p>
<p>I plan to enhance the model by introducing heterogeneity. To begin, I will incorporate individual heterogeneity based on customer attributes, specifically through an interaction term between price and usage (minutes). This addition aims to capture the nuanced effects of pricing on different customer segments, enriching the model’s predictive accuracy and relevance.</p>
</section>
<section id="add-heterogenity" class="level2">
<h2 class="anchored" data-anchor-id="add-heterogenity">Add Heterogenity</h2>
<p>To introduce heterogeneity into the model, I will integrate an interaction term between “price” and “total minutes” used. This approach is based on the hypothesis that customers who use their phones more extensively may be willing to pay a higher price for their phone services. By including this interaction term, I aim to examine the relationship between phone usage and price sensitivity. A positive coefficient for this interaction would support the hypothesis, indicating that increased usage correlates with a greater willingness to pay, thus adding a layer of individual behavioral variation to the model. This enhancement should provide deeper insights into consumer behavior and improve the model’s ability to predict responses to pricing strategies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a> out5 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> phone_id <span class="sc">+</span> price <span class="sc">+</span> price<span class="sc">:</span>total_minutes <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summary</span>(out5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ phone_id + price + price:total_minutes | 
    0, data = mdat1, method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 6.41E-07 
gradient close to zero 

Coefficients :
                       Estimate  Std. Error z-value  Pr(&gt;|z|)    
phone_idA2           2.1881e-01  2.2622e-01  0.9672  0.333422    
phone_idH1          -1.2755e+00  1.7421e-01 -7.3215 2.451e-13 ***
phone_idH2          -9.2244e-01  1.3110e-01 -7.0361 1.977e-12 ***
phone_idS1          -3.1735e-01  1.1303e-01 -2.8076  0.004991 ** 
phone_idS2          -5.7209e-01  1.3518e-01 -4.2322 2.314e-05 ***
price               -3.0727e-02  3.5267e-03 -8.7126 &lt; 2.2e-16 ***
price:total_minutes  1.8024e-05  2.5063e-06  7.1914 6.413e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1640.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">brand_hit_rate</span>(mdat1, out5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4032922</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">product_hit_rate</span>(mdat1, out5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.287037</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ll_ratio</span>(mdat1, out5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05803016</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>    <span class="co"># plot each individual's probability of choosing phone A1</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">myplot</span>(mdat1, out5, <span class="st">"A1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="summary-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-1">Summary 1</h2>
<p>By incorporating the interaction term between price and total minutes used in our model, we have differentiated the impact of price on the utility derived by different consumers. This adjustment reveals that even among consumers facing the same phone discount, their probabilities of purchase can vary significantly due to their distinct phone usage behaviors.</p>
<p>To clarify, let’s consider the structural transformation of the model component concerning price. Originally, the model might have included separate terms for the effect of price and the interaction of price with minutes used:</p>
<p>Utility=… +(ßprice x price)+(ßint x price x total minutes)+ …</p>
<p>This can be reformulated as:</p>
<p>Utility=… +(ßprice + ßint x total minutes) x price + …</p>
<p>In this formulation ßprice is typically negative, indicating that higher prices generally decrease utility. However, when ßint is positive, it implies that consumers with higher usage (more total minutes) exhibit a less negative—or less sensitive—response to price increases. This is because the addition of ßint* Totalminutets to ßprice reduces the absolute value of the negative price coefficient.</p>
<p>Essentially, this model transformation clarifies that as total minutes increase, the combined coefficient on price approaches zero, indicating a reduction in price sensitivity for high-usage consumers.</p>
<p>Given these theoretical considerations, it is now pertinent to delve into the data to explore how this heterogeneous model predicts consumer choice behavior. By examining the empirical effects of these variables, we can validate the model’s assumptions and refine our understanding of consumer dynamics in the market.</p>
</section>
<section id="deeper-dive-into-the-data" class="level2">
<h2 class="anchored" data-anchor-id="deeper-dive-into-the-data">Deeper Dive into the data</h2>
<p>I will now undertake a thorough analysis of the data to ascertain how effectively the heterogeneous model forecasts consumer choice behavior. This deep dive is essential to validate the theoretical constructs of the model and to refine our understanding of how consumer attributes, such as phone usage, influence their sensitivity to pricing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># grab the data for 2 consumers</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>        x1 <span class="ot">&lt;-</span> sub1 <span class="sc">|&gt;</span> <span class="fu">filter</span>(customer_id <span class="sc">==</span> <span class="dv">9</span>) <span class="sc">|&gt;</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">mutate</span>(<span class="at">A2 =</span> phone_id <span class="sc">==</span> <span class="st">"A2"</span>, </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">S1 =</span> phone_id <span class="sc">==</span> <span class="st">"S1"</span>, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">S2 =</span> phone_id <span class="sc">==</span> <span class="st">"S2"</span>, </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                              <span class="at">H1 =</span> phone_id <span class="sc">==</span> <span class="st">"H1"</span>, </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                              <span class="at">H2 =</span> phone_id <span class="sc">==</span> <span class="st">"H2"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                              <span class="at">ptm =</span> price <span class="sc">*</span> total_minutes) <span class="sc">|&gt;</span> </span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">select</span>(A2, H1, H2, S1, S2, price, ptm) <span class="sc">|&gt;</span> </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">as.matrix</span>()</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>        x2 <span class="ot">&lt;-</span> sub1 <span class="sc">|&gt;</span> <span class="fu">filter</span>(customer_id <span class="sc">==</span> <span class="dv">13</span>) <span class="sc">|&gt;</span> </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">mutate</span>(<span class="at">A2 =</span> phone_id <span class="sc">==</span> <span class="st">"A2"</span>, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>                              <span class="at">S1 =</span> phone_id <span class="sc">==</span> <span class="st">"S1"</span>, </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                              <span class="at">S2 =</span> phone_id <span class="sc">==</span> <span class="st">"S2"</span>, </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>                              <span class="at">H1 =</span> phone_id <span class="sc">==</span> <span class="st">"H1"</span>, </span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>                              <span class="at">H2 =</span> phone_id <span class="sc">==</span> <span class="st">"H2"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>                              <span class="at">ptm =</span> price <span class="sc">*</span> total_minutes) <span class="sc">|&gt;</span> </span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">select</span>(A2, S1, S2, H1, H2, price, ptm) <span class="sc">|&gt;</span> </span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">as.matrix</span>()</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>        <span class="co"># notice how the interaction variable (ptm) is different for the two consumers</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>        x1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A2 H1 H2 S1 S2 price     ptm
[1,]  0  0  0  0  0 764.1 1172627
[2,]  1  0  0  0  0 999.0 1533117
[3,]  0  0  0  1  0 799.0 1226187
[4,]  0  0  0  0  1 899.0 1379652
[5,]  0  1  0  0  0 749.0 1149454
[6,]  0  0  1  0  0 799.0 1226187</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>        x2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A2 S1 S2 H1 H2 price      ptm
[1,]  0  0  0  0  0   849 836425.3
[2,]  1  0  0  0  0   999 984203.6
[3,]  0  1  0  0  0   799 787165.9
[4,]  0  0  1  0  0   899 885684.7
[5,]  0  0  0  1  0   749 737906.4
[6,]  0  0  0  0  1   799 787165.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>        <span class="co"># This is almost entirely driven by the variation in total minutes for the two consumers.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>        cust_dat <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">9</span>,<span class="dv">13</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(total_minutes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 1
  total_minutes
          &lt;dbl&gt;
1         1535.
2          985.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>        <span class="co"># calculate probabilities of purchase for the six phones for each of the two consumers</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>        beta_hat <span class="ot">&lt;-</span> <span class="fu">coef</span>(out5)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>        xb1 <span class="ot">&lt;-</span> <span class="fu">t</span>(x1 <span class="sc">%*%</span> beta_hat)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>        xb2 <span class="ot">&lt;-</span> <span class="fu">t</span>(x2 <span class="sc">%*%</span> beta_hat)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>        example_shares <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>            <span class="fu">round</span>(<span class="fu">exp</span>(xb1) <span class="sc">/</span> <span class="fu">rowSums</span>(<span class="fu">exp</span>(xb1)), <span class="dv">3</span>),</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>            <span class="fu">round</span>(<span class="fu">exp</span>(xb2) <span class="sc">/</span> <span class="fu">rowSums</span>(<span class="fu">exp</span>(xb2)), <span class="dv">3</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>        <span class="fu">colnames</span>(example_shares) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A1"</span>, <span class="st">"A2"</span>, <span class="st">"S1"</span>, <span class="st">"S2"</span>, <span class="st">"H1"</span>, <span class="st">"H2"</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>        example_shares</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        A1    A2    S1    S2    H1    H2
[1,] 0.305 0.184 0.199 0.114 0.089 0.109
[2,] 0.177 0.031 0.094 0.037 0.470 0.191</code></pre>
</div>
</div>
</section>
<section id="summary-2" class="level2">
<h2 class="anchored" data-anchor-id="summary-2">Summary 2</h2>
<p>Observations from the model indicate that the probabilities of purchasing different phones vary significantly between consumers. For instance, I noted that the first consumer has an estimated 30.5% probability of purchasing the small Apple phone (A1), while this probability drops to 17.7% for the second consumer. In contrast, the second consumer shows a 47.0% probability of purchasing the small Huawei phone (H1), compared to only an 8.9% probability for the first consumer.</p>
<p>This discrepancy can be attributed to the differences in phone usage between the two consumers. The second consumer, who uses their phone substantially less than the first, is predicted by the model to be more sensitive to price. This increased price sensitivity leads the second consumer to prefer the more affordable H1 phone over the more expensive A1 phone.</p>
<p>With these insights, I will now return to refining the modeling process…</p>
</section>
<section id="add-heterogeneity-via-a-segment-interactions" class="level2">
<h2 class="anchored" data-anchor-id="add-heterogeneity-via-a-segment-interactions">Add Heterogeneity Via a Segment Interactions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>  <span class="co"># compare brand-dummy only model before/after adding segments</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>        out1 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple <span class="sc">+</span> samsung <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple + samsung | 0, data = mdat1, 
    method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
3 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.00849 
successive function values within tolerance limits 

Coefficients :
        Estimate Std. Error z-value Pr(&gt;|z|)  
apple   0.197455   0.080071  2.4660  0.01366 *
samsung 0.185829   0.080281  2.3147  0.02063 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1737.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3559671</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002181383</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>        out6 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple<span class="sc">:</span>segment <span class="sc">+</span> samsung<span class="sc">:</span>segment <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple:segment + samsung:segment | 0, 
    data = mdat1, method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 3.31E-06 
successive function values within tolerance limits 

Coefficients :
                   Estimate Std. Error z-value  Pr(&gt;|z|)    
apple:segment1   -0.0645385  0.2074983 -0.3110 0.7557767    
apple:segment2    0.0073260  0.1210463  0.0605 0.9517394    
apple:segment3    0.4946962  0.1268762  3.8990 9.657e-05 ***
segment1:samsung  0.6061358  0.1794351  3.3780 0.0007301 ***
segment2:samsung  0.1177830  0.1178511  0.9994 0.3175902    
segment3:samsung  0.0099503  0.1410709  0.0705 0.9437684    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1721.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4166667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01161601</code></pre>
</div>
</div>
</section>
<section id="summary-3" class="level2">
<h2 class="anchored" data-anchor-id="summary-3">Summary 3</h2>
<p>In examining the coefficients between models 1 and 6, I observed notable variations. Initially, in model 1, the coefficient for Apple was 0.197. However, when I introduced interactions between Apple and segment dummies, the coefficients adjusted to -0.06, 0.007, and 0.49 respectively. The original value of 0.197 seems to act as a weighted average of these new segment-specific coefficients, providing a broader, albeit less detailed, perspective.</p>
<p>With this refined model, more nuanced insights emerge: relative to consumers preferring Huawei phones (the baseline), consumers in segment 1 exhibit a decreased preference for Apple phones, those in segment 2 show a slight increase in preference, and segment 3 consumers demonstrate a significantly heightened preference for Apple. This granularity allows for a deeper understanding of brand preferences across different consumer segments.</p>
</section>
<section id="brand-dummy-and-price-models" class="level2">
<h2 class="anchored" data-anchor-id="brand-dummy-and-price-models">Brand-Dummy and Price Models</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># compare brand-dummy + price model before/after adding segments </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>        out2 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple <span class="sc">+</span> samsung <span class="sc">+</span> price <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple + samsung + price | 0, data = mdat1, 
    method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.000129 
successive function values within tolerance limits 

Coefficients :
           Estimate  Std. Error  z-value  Pr(&gt;|z|)    
apple    1.05865609  0.10876661   9.7333 &lt; 2.2e-16 ***
samsung  0.63450323  0.08959903   7.0816 1.425e-12 ***
price   -0.00619721  0.00058165 -10.6545 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1677</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">product_hit_rate</span>(mdat1, out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2479424</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3549383</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03709335</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>        out7 <span class="ot">&lt;-</span>  <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple<span class="sc">:</span>segment <span class="sc">+</span> samsung<span class="sc">:</span>segment <span class="sc">+</span> price<span class="sc">:</span>segment <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple:segment + samsung:segment + price:segment | 
    0, data = mdat1, method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.000745 
successive function values within tolerance limits 

Coefficients :
                    Estimate  Std. Error z-value  Pr(&gt;|z|)    
apple:segment1    1.02566857  0.27908247  3.6751 0.0002377 ***
apple:segment2    0.75968029  0.16565164  4.5860 4.518e-06 ***
apple:segment3    1.37531278  0.17076980  8.0536 8.882e-16 ***
segment1:samsung  1.18831667  0.20759621  5.7242 1.039e-08 ***
segment2:samsung  0.50237709  0.13212776  3.8022 0.0001434 ***
segment3:samsung  0.47240850  0.15413564  3.0649 0.0021775 ** 
segment1:price   -0.00773883  0.00146750 -5.2735 1.339e-07 ***
segment2:price   -0.00537932  0.00088152 -6.1023 1.045e-09 ***
segment3:price   -0.00641654  0.00091503 -7.0124 2.343e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1659.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4176955</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">product_hit_rate</span>(mdat1, out7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3014403</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04697134</code></pre>
</div>
</div>
</section>
<section id="summary-4" class="level2">
<h2 class="anchored" data-anchor-id="summary-4">Summary 4</h2>
<p>I will now concentrate on price sensitivity. By incorporating segment-specific price variables into the model, I am able to estimate distinct price sensitivities for each consumer segment. From this analysis, it is evident that consumers in segment 1 exhibit greater price sensitivity, whereas those in segment 2 demonstrate a lesser sensitivity to price changes. This differentiation allows for a more nuanced understanding of how price impacts different groups within the market.</p>
</section>
<section id="comparing-brand-dummy" class="level2">
<h2 class="anchored" data-anchor-id="comparing-brand-dummy">Comparing Brand-Dummy</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compare brand-dummy + price + size model before/after adding segments </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>        out3 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple <span class="sc">+</span> samsung <span class="sc">+</span> price <span class="sc">+</span> screen_size<span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple + samsung + price + screen_size | 
    0, data = mdat1, method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.000119 
successive function values within tolerance limits 

Coefficients :
              Estimate Std. Error z-value  Pr(&gt;|z|)    
apple        0.9983423  0.1443294  6.9171 4.610e-12 ***
samsung      0.6357234  0.0894121  7.1100 1.160e-12 ***
price       -0.0056366  0.0010562 -5.3366 9.473e-08 ***
screen_size -0.1416883  0.2226515 -0.6364    0.5245    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1676.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">product_hit_rate</span>(mdat1, out3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2479424</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3549383</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03721033</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>        out8 <span class="ot">&lt;-</span>  <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple<span class="sc">:</span>segment <span class="sc">+</span> samsung<span class="sc">:</span>segment <span class="sc">+</span> price<span class="sc">:</span>segment </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span> screen_size<span class="sc">:</span>segment <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple:segment + samsung:segment + price:segment + 
    screen_size:segment | 0, data = mdat1, method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 0.00393 
successive function values within tolerance limits 

Coefficients :
                       Estimate Std. Error z-value  Pr(&gt;|z|)    
apple:segment1        0.7743060  0.3923699  1.9734 0.0484491 *  
apple:segment2        0.8032405  0.2160772  3.7174 0.0002013 ***
apple:segment3        1.2686962  0.2265921  5.5990 2.156e-08 ***
segment1:samsung      1.1593536  0.2077670  5.5801 2.404e-08 ***
segment2:samsung      0.5004437  0.1324940  3.7771 0.0001587 ***
segment3:samsung      0.4792747  0.1538156  3.1159 0.0018338 ** 
segment1:price       -0.0055226  0.0028390 -1.9453 0.0517435 .  
segment2:price       -0.0057829  0.0015599 -3.7073 0.0002095 ***
segment3:price       -0.0053967  0.0016963 -3.1815 0.0014654 ** 
segment1:screen_size -0.4904160  0.5378925 -0.9117 0.3619077    
segment2:screen_size  0.1009087  0.3221117  0.3133 0.7540737    
segment3:screen_size -0.2758123  0.3860816 -0.7144 0.4749868    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1659.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4053498</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">product_hit_rate</span>(mdat1, out8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.281893</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04739159</code></pre>
</div>
</div>
</section>
<section id="summary-5" class="level2">
<h2 class="anchored" data-anchor-id="summary-5">Summary 5</h2>
<p>Last project(5), I observed that including screen size in a model that already accounts for brand and price does not significantly enhance the model’s performance. This observation is supported by the statistical insignificance of the screen size coefficients and the very marginal changes in hit rates and likelihood ratios. These results suggest that screen size, within the context of this model, may not be a decisive factor in predicting consumer choices as compared to brand and price.</p>
</section>
<section id="building-a-model-with-segment-specific-and-individual-specific-heterogeneity" class="level2">
<h2 class="anchored" data-anchor-id="building-a-model-with-segment-specific-and-individual-specific-heterogeneity">Building a Model with Segment-Specific and Individual-Specific Heterogeneity</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Construct a model with both segment-specific and individual-specific heterogeneity</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>        out9 <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> apple<span class="sc">:</span>segment <span class="sc">+</span> samsung<span class="sc">:</span>segment <span class="sc">+</span> </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>                           price<span class="sc">:</span>segment <span class="sc">+</span> screen_size<span class="sc">:</span>segment <span class="sc">+</span> </span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>                           price<span class="sc">:</span>total_minutes<span class="sc">:</span>segment <span class="sc">|</span> <span class="dv">0</span>, <span class="at">data=</span>mdat1)</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>(out9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ apple:segment + samsung:segment + price:segment + 
    screen_size:segment + price:total_minutes:segment | 0, data = mdat1, 
    method = "nr")

Frequencies of alternatives:choice
       1        2        3        4        5        6 
0.239712 0.116255 0.253086 0.098765 0.148148 0.144033 

nr method
4 iterations, 0h:0m:0s 
g'(-H)^-1g = 2.77E-07 
gradient close to zero 

Coefficients :
                        Estimate  Std. Error z-value  Pr(&gt;|z|)    
apple:segment1        7.6450e-01  3.9285e-01  1.9460 0.0516533 .  
apple:segment2        8.8067e-01  2.1797e-01  4.0404 5.337e-05 ***
apple:segment3        1.3531e+00  2.2920e-01  5.9036 3.556e-09 ***
segment1:samsung      1.1616e+00  2.0804e-01  5.5832 2.361e-08 ***
segment2:samsung      5.5667e-01  1.3421e-01  4.1477 3.359e-05 ***
segment3:samsung      5.2233e-01  1.5541e-01  3.3609 0.0007769 ***
segment1:price       -1.5977e-02  1.3490e-02 -1.1844 0.2362662    
segment2:price       -3.0937e-02  4.7523e-03 -6.5098 7.524e-11 ***
segment3:price       -2.8993e-02  6.0525e-03 -4.7902 1.666e-06 ***
segment1:screen_size -5.1712e-01  5.3826e-01 -0.9607 0.3366917    
segment2:screen_size  1.5741e-01  3.2221e-01  0.4885 0.6251769    
segment3:screen_size -1.9223e-01  3.8722e-01 -0.4964 0.6195940    
segment1:price        8.2628e-06  1.0374e-05  0.7965 0.4257536    
segment2:price        1.9021e-05  3.2980e-06  5.7676 8.039e-09 ***
segment3:price        1.7021e-05  4.1106e-06  4.1409 3.460e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -1632</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">brand_hit_rate</span>(mdat1, out9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4269547</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">product_hit_rate</span>(mdat1, out9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2973251</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ll_ratio</span>(mdat1, out9)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06294537</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>    <span class="co"># plot each individual's probability of choosing phone A1 or S2</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">myplot</span>(mdat1, out9, <span class="st">"A1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">myplot</span>(mdat1, out9, <span class="st">"S2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="summary-6" class="level2">
<h2 class="anchored" data-anchor-id="summary-6">Summary 6</h2>
<p>Concerns about overfitting are paramount, as they could diminish our model’s predictive accuracy. To address this, I propose selecting a model through the method of 10-fold cross-validation. This technique will enable a rigorous evaluation of the model’s performance across multiple subsets of the data, providing a more robust indication of its generalizability. Furthermore, I will focus on the mean squared prediction error (MSPE) as a key metric for assessing the accuracy of our predictions. This systematic approach ensures that we adopt a model not just tailored to fit the training data but also capable of delivering reliable predictions on new, unseen data.</p>
</section>
<section id="which-models-predict-better" class="level2">
<h2 class="anchored" data-anchor-id="which-models-predict-better">Which models predict better?</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>    cv_mspe <span class="ot">&lt;-</span> <span class="cf">function</span>(model, data, <span class="at">k=</span><span class="dv">10</span>, <span class="at">seed=</span><span class="dv">4321</span>) {</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>        <span class="co"># control psuedo random numbers</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">set.seed</span>(seed)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>        <span class="co"># randomly assign each customer (J rows) to one of k folds</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>        N <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>customer_id))   <span class="co"># number of customers</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>        J <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(data<span class="sc">$</span>phone_id))      <span class="co"># number of products</span></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>        fold <span class="ot">&lt;-</span> <span class="fu">rep</span>((<span class="dv">1</span><span class="sc">:</span>N) <span class="sc">%%</span> k <span class="sc">+</span> <span class="dv">1</span>, <span class="at">each=</span>J)    <span class="co"># rep replicates list elements</span></span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># %% is a modulus element, so what we're doing here is computing the remainder when</span></span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>        <span class="co"># dividing 1:N by (k+1). So mod(customer_id,10)+1 is always an integer between 1</span></span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># and 10. We repeat that 6 times for each customer, to match the mdat1 observations</span></span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># preallocate the prediction storage</span></span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a>        preds <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">length=</span><span class="fu">nrow</span>(data))     </span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># loop over folds </span></span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>k) {</span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a>            <span class="co"># create row indices for training &amp; prediction observations      </span></span>
<span id="cb89-21"><a href="#cb89-21" aria-hidden="true" tabindex="-1"></a>            row_ids_train <span class="ot">&lt;-</span> fold <span class="sc">!=</span> i     <span class="co"># which rows to keep in for training</span></span>
<span id="cb89-22"><a href="#cb89-22" aria-hidden="true" tabindex="-1"></a>            row_ids_test  <span class="ot">&lt;-</span> <span class="sc">!</span>row_ids_train  <span class="co"># which rows to hold out for prediction</span></span>
<span id="cb89-23"><a href="#cb89-23" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb89-24"><a href="#cb89-24" aria-hidden="true" tabindex="-1"></a>            <span class="co"># fit/train model on training data</span></span>
<span id="cb89-25"><a href="#cb89-25" aria-hidden="true" tabindex="-1"></a>            out  <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(<span class="fu">formula</span>(model), <span class="at">data=</span>data[row_ids_train,])</span>
<span id="cb89-26"><a href="#cb89-26" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb89-27"><a href="#cb89-27" aria-hidden="true" tabindex="-1"></a>            <span class="co"># predict choice probabilities for prediction data</span></span>
<span id="cb89-28"><a href="#cb89-28" aria-hidden="true" tabindex="-1"></a>            yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> data[row_ids_test,])</span>
<span id="cb89-29"><a href="#cb89-29" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb89-30"><a href="#cb89-30" aria-hidden="true" tabindex="-1"></a>            <span class="co"># store yhat values for prediction data</span></span>
<span id="cb89-31"><a href="#cb89-31" aria-hidden="true" tabindex="-1"></a>            preds[row_ids_test] <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">t</span>(yhat))</span>
<span id="cb89-32"><a href="#cb89-32" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb89-33"><a href="#cb89-33" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb89-34"><a href="#cb89-34" aria-hidden="true" tabindex="-1"></a>        <span class="co"># calculate mse</span></span>
<span id="cb89-35"><a href="#cb89-35" aria-hidden="true" tabindex="-1"></a>        mspe <span class="ot">&lt;-</span> <span class="fu">mean</span>((data<span class="sc">$</span>choice <span class="sc">-</span> preds)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb89-36"><a href="#cb89-36" aria-hidden="true" tabindex="-1"></a>        <span class="fu">return</span>(mspe)</span>
<span id="cb89-37"><a href="#cb89-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb89-38"><a href="#cb89-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb89-39"><a href="#cb89-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># calculate the MSE's for each model</span></span>
<span id="cb89-40"><a href="#cb89-40" aria-hidden="true" tabindex="-1"></a>    mspe <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">length=</span><span class="dv">9</span>)</span>
<span id="cb89-41"><a href="#cb89-41" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out1, mdat1)</span>
<span id="cb89-42"><a href="#cb89-42" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out2, mdat1)</span>
<span id="cb89-43"><a href="#cb89-43" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out3, mdat1)</span>
<span id="cb89-44"><a href="#cb89-44" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out4, mdat1)</span>
<span id="cb89-45"><a href="#cb89-45" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out5, mdat1)</span>
<span id="cb89-46"><a href="#cb89-46" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out6, mdat1)</span>
<span id="cb89-47"><a href="#cb89-47" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out7, mdat1)</span>
<span id="cb89-48"><a href="#cb89-48" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">8</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out8, mdat1)</span>
<span id="cb89-49"><a href="#cb89-49" aria-hidden="true" tabindex="-1"></a>    mspe[<span class="dv">9</span>] <span class="ot">&lt;-</span> <span class="fu">cv_mspe</span>(out9, mdat1)</span>
<span id="cb89-50"><a href="#cb89-50" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb89-51"><a href="#cb89-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># plot the MSE's to compare them</span></span>
<span id="cb89-52"><a href="#cb89-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tibble</span>(<span class="at">mod_id=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">mspe=</span>mspe) <span class="sc">|&gt;</span> </span>
<span id="cb89-53"><a href="#cb89-53" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>mod_id, <span class="at">y=</span>mspe)) <span class="sc">+</span></span>
<span id="cb89-54"><a href="#cb89-54" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb89-55"><a href="#cb89-55" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_line</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylim</span>(<span class="fu">c</span>(<span class="dv">0</span>, .<span class="dv">14</span>))  <span class="co"># adjustment to show the abs differences</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;ScaleContinuousPosition&gt;
 Range:  
 Limits:    0 -- 0.14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>    <span class="co"># that adjustment helps to show why mspe is only 1 factor among several when </span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">#    choosing a model specification</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># which model has the lowest cross-validated mean-squared-error?</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">which.min</span>(mspe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
</div>
</section>
<section id="summary-7" class="level2">
<h2 class="anchored" data-anchor-id="summary-7">Summary 7</h2>
<p>This model, referred to as “out9,” has demonstrated the most robust performance based on our criteria, which include the hit rate and the log-likelihood ratio index. Furthermore, it effectively incorporates segment-level heterogeneity, enriching its analytical depth. I will utilize this specific model configuration for the subsequent two projects, and further exploring its capabilities and shows more variety predictive power within various consumer segments.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>